import { canViewReports, isAdminRole } from "../../utils/roles";
import { hasAccountantPermission } from "../../utils/accountantPermissions";

/** @typedef {{ path: string, label: string, icon: string, section?: string, badgePath?: string, permissionKey?: string, visible: (role: string, permissions?: Record<string, boolean>|null) => boolean }} NavItem */

function canSeeReportPage(role, permissions, permissionKey) {
  if (!canViewReports(role)) return false;
  if (!permissionKey) return true;
  return hasAccountantPermission(role, permissions, permissionKey);
}

/** @type {NavItem[]} */
export const OFFICE_NAV = [
  {
    path: "/reports",
    label: "لوحة التحكم",
    icon: "dashboard",
    section: "overview",
    permissionKey: "dashboard",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "dashboard"),
  },
  {
    path: "/manage-products",
    label: "المنتجات",
    icon: "products",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/customers",
    label: "العملاء",
    icon: "customers",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/suppliers",
    label: "الموردون",
    icon: "suppliers",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/units",
    label: "الوحدات",
    icon: "products",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/inventory",
    label: "جرد المخزون",
    icon: "inventory",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/bakery-supplies",
    label: "مواد المخبز",
    icon: "inventory",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/warehouses",
    label: "المستودعات",
    icon: "warehouses",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/expiry",
    label: "الصلاحية",
    icon: "expiry",
    section: "catalog",
    badgePath: "/expiry",
    permissionKey: "expiry",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "expiry"),
  },
  {
    path: "/finance",
    label: "المالية",
    icon: "finance",
    section: "finance",
    permissionKey: "finance",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "finance"),
  },
  {
    path: "/expenses",
    label: "المصروفات",
    icon: "expenses",
    section: "finance",
    permissionKey: "expenses",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "expenses"),
  },
  {
    path: "/sales-reports",
    label: "تقارير المبيعات",
    icon: "finance",
    section: "finance",
    permissionKey: "sales_reports",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "sales_reports"),
  },
  {
    path: "/shift-audit",
    label: "الورديات",
    icon: "shifts",
    section: "finance",
    badgePath: "/shift-audit",
    permissionKey: "shift_audit",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "shift_audit"),
  },
  {
    path: "/sales-by-price",
    label: "المبيعات حسب السعر",
    icon: "finance",
    section: "finance",
    permissionKey: "sales_by_price",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "sales_by_price"),
  },
  {
    path: "/banks",
    label: "البنوك والشيكات",
    icon: "banks",
    section: "finance",
    permissionKey: "banks",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "banks"),
  },
  {
    path: "/account-statement",
    label: "كشف حساب",
    icon: "vouchers",
    section: "finance",
    permissionKey: "account_statement",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "account_statement"),
  },
  {
    path: "/import-supplier-balances",
    label: "استيراد أرصدة الموردين",
    icon: "suppliers",
    section: "finance",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/vouchers/receipt",
    label: "سند قبض",
    icon: "vouchers",
    section: "invoices",
    permissionKey: "vouchers",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "vouchers"),
  },
  {
    path: "/vouchers/payment",
    label: "سند صرف",
    icon: "vouchers",
    section: "invoices",
    permissionKey: "vouchers",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "vouchers"),
  },
  {
    path: "/purchases",
    label: "فتورة مشتريات",
    icon: "purchases",
    section: "invoices",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/sales-invoices",
    label: "فتورة مبيعات",
    icon: "customers",
    section: "invoices",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/refunds",
    label: "الاسترجاعات",
    icon: "refunds",
    section: "operations",
    permissionKey: "refunds",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "refunds"),
  },
  {
    path: "/refund-approvals",
    label: "موافقات الاسترجاع",
    icon: "refunds",
    section: "operations",
    badgePath: "/refund-approvals",
    permissionKey: "refund_approvals",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "refund_approvals"),
  },
  {
    path: "/on-account-approvals",
    label: "موافقات الذمة",
    icon: "vouchers",
    section: "operations",
    badgePath: "/on-account-approvals",
    permissionKey: "on_account_approvals",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "on_account_approvals"),
  },
  {
    path: "/advance-approvals",
    label: "موافقات السلف",
    icon: "vouchers",
    section: "operations",
    badgePath: "/advance-approvals",
    permissionKey: "advance_approvals",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "advance_approvals"),
  },
  {
    path: "/marketing",
    label: "التسويق",
    icon: "marketing",
    section: "operations",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/manage-users",
    label: "الحسابات",
    icon: "users",
    section: "admin",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/cashier-payroll",
    label: "رواتب الكاشير",
    icon: "shifts",
    section: "admin",
    permissionKey: "employee_payroll",
    visible: (role, permissions) => canSeeReportPage(role, permissions, "employee_payroll"),
  },
  {
    path: "/settings",
    label: "الإعدادات",
    icon: "settings",
    section: "admin",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/settings/currency",
    label: "العملات",
    icon: "settings",
    section: "admin",
    visible: (role) => isAdminRole(role),
  },
];

export const NAV_SECTION_LABELS = {
  overview: "نظرة عامة",
  catalog: "المخزون والمنتجات",
  invoices: "فواتير",
  finance: "المالية والتقارير",
  operations: "العمليات",
  admin: "الإدارة",
};

export const ROUTE_TITLES = {
  "/reports": "لوحة التحكم",
  "/manage-products": "إدارة المنتجات",
  "/manage-users": "إدارة الحسابات",
  "/finance": "المالية ودفعات الموردين",
  "/sales-reports": "تقارير المبيعات",
  "/shift-audit": "تدقيق الورديات",
  "/cashier-payroll": "رواتب الكاشير",
  "/refunds": "الاسترجاعات",
  "/refund-approvals": "موافقات الاسترجاع",
  "/on-account-approvals": "موافقات الذمة",
  "/advance-approvals": "موافقات السلف",
  "/settings": "إعدادات المتجر",
  "/settings/currency": "إعدادات العملات",
  "/inventory": "جرد المخزون",
  "/bakery-supplies": "مواد المخبز",
  "/expiry": "تقارير الصلاحية",
  "/sales-by-price": "المبيعات حسب سعر البيع",
  "/customers": "إدارة العملاء",
  "/suppliers": "إدارة الموردين",
  "/purchases": "فتورة مشتريات",
  "/sales-invoices": "فتورة مبيعات",
  "/units": "الوحدات",
  "/expenses": "المصروفات",
  "/banks": "البنوك والشيكات",
  "/vouchers/receipt": "سند قبض",
  "/vouchers/payment": "سند صرف",
  "/deliveries": "التوصيل والاستلام",
  "/marketing": "التسويق والعروض",
  "/warehouses": "المستودعات",
  "/account-statement": "كشف حساب",
  "/import-supplier-balances": "استيراد أرصدة الموردين",
};

/** Map route paths to permission keys for route guards. */
export const ROUTE_PERMISSION_KEYS = {
  "/reports": "dashboard",
  "/finance": "finance",
  "/sales-reports": "sales_reports",
  "/shift-audit": "shift_audit",
  "/cashier-payroll": "employee_payroll",
  "/refunds": "refunds",
  "/refund-approvals": "refund_approvals",
  "/on-account-approvals": "on_account_approvals",
  "/advance-approvals": "advance_approvals",
  "/expiry": "expiry",
  "/sales-by-price": "sales_by_price",
  "/expenses": "expenses",
  "/deliveries": "deliveries",
  "/banks": "banks",
  "/account-statement": "account_statement",
  "/vouchers/receipt": "vouchers",
  "/vouchers/payment": "vouchers",
  "/suppliers/:supplierId/statement": "account_statement",
};
