import { canViewReports, isAdminRole } from "../../utils/roles";

/** @typedef {{ path: string, label: string, icon: string, section?: string, visible: (role: string) => boolean }} NavItem */

/** @type {NavItem[]} */
export const OFFICE_NAV = [
  {
    path: "/reports",
    label: "لوحة التحكم",
    icon: "dashboard",
    section: "overview",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/manage-products",
    label: "المنتجات",
    icon: "products",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/customers",
    label: "العملاء",
    icon: "customers",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/suppliers",
    label: "الموردون",
    icon: "suppliers",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/purchases",
    label: "المشتريات",
    icon: "purchases",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/inventory",
    label: "جرد المخزون",
    icon: "inventory",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/warehouses",
    label: "المستودعات",
    icon: "warehouses",
    section: "catalog",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/finance",
    label: "المالية",
    icon: "finance",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/expenses",
    label: "المصروفات",
    icon: "expenses",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/shift-audit",
    label: "الورديات",
    icon: "shifts",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/refunds",
    label: "الاسترجاعات",
    icon: "refunds",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/refund-approvals",
    label: "موافقات الاسترجاع",
    icon: "refunds",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/expiry",
    label: "الصلاحية",
    icon: "expiry",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/sales-by-price",
    label: "المبيعات حسب السعر",
    icon: "finance",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/banks",
    label: "البنوك والشيكات",
    icon: "banks",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/vouchers",
    label: "السندات",
    icon: "vouchers",
    section: "finance",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/deliveries",
    label: "التوصيل",
    icon: "deliveries",
    section: "operations",
    visible: (role) => canViewReports(role),
  },
  {
    path: "/marketing",
    label: "التسويق",
    icon: "marketing",
    section: "operations",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/manage-users",
    label: "الحسابات",
    icon: "users",
    section: "admin",
    visible: (role) => isAdminRole(role),
  },
  {
    path: "/settings",
    label: "الإعدادات",
    icon: "settings",
    section: "admin",
    visible: (role) => isAdminRole(role),
  },
];

export const NAV_SECTION_LABELS = {
  overview: "نظرة عامة",
  catalog: "المخزون والمبيعات",
  finance: "المالية والتقارير",
  operations: "العمليات",
  admin: "الإدارة",
};

export const ROUTE_TITLES = {
  "/reports": "لوحة التحكم",
  "/manage-products": "إدارة المنتجات",
  "/manage-users": "إدارة الحسابات",
  "/finance": "المالية ودفعات الموردين",
  "/shift-audit": "تدقيق الورديات",
  "/refunds": "الاسترجاعات",
  "/refund-approvals": "موافقات الاسترجاع",
  "/settings": "إعدادات المتجر",
  "/inventory": "جرد المخزون",
  "/expiry": "تقارير الصلاحية",
  "/sales-by-price": "المبيعات حسب سعر البيع",
  "/customers": "إدارة العملاء",
  "/suppliers": "إدارة الموردين",
  "/purchases": "المشتريات",
  "/expenses": "المصروفات",
  "/banks": "البنوك والشيكات",
  "/vouchers": "السندات",
  "/deliveries": "التوصيل والاستلام",
  "/marketing": "التسويق والعروض",
  "/warehouses": "المستودعات",
};
